"""add row used answers to game

Revision ID: 66017a9c41ac
Revises: b59c8abd1248
Create Date: 2022-09-15 17:40:46.971565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66017a9c41ac'
down_revision = 'b59c8abd1248'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('used_answers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'used_answers')
    # ### end Alembic commands ###
